# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Portfolio & blog
email: contact@rjlopez.me
description: >-
  Hi! This is my personal site :)
  It includes a portfolio & blog.
  I write things about Software Architecture & Web technologies.
permalink: /blog/:title/
# Build settings
sass:
  sass_dir: _sass
theme: plainwhite
plugins:
  # jekyll-feed
  - jekyll-seo-tag

plainwhite:
  name: R.J. LÃ³pez
  tagline: Software Developer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: rjlopez_
    github:  rjlopezdev
    linkedIn: in/rjlopezdev
